// Shared config for the arcwork judge roster — 12 independent evaluator
// identities, each backed by a different model via OpenRouter (falls back to
// a local Ollama model of the same name if OPENROUTER_API_KEY isn't set — see
// aiEvaluateOpenRouter / aiEvaluateLocal in lib.mjs). A client picks one at
// job-creation time (see src/lib/presets.ts on the frontend); this file is
// the source of truth the agents read from.
//
// Every judge's private key lives in agents/.env under its own pkEnv name,
// generated by setup.mjs. Every judge's ANS name is registered on-chain via
// register-judges.mjs so it resolves to "<ansName>.arc" across the site, and
// every judge is also registered as an ERC-8004 agent identity via
// register-erc8004.mjs (see src/lib/presets.ts for the resulting agentId).
export const JUDGES = [
  // ── Original 4 — same wallets, renamed personas, moved to OpenRouter ──
  {
    key: "judge",
    pkEnv: "EVALUATOR_PK",
    ansName: "arcwork-llama",
    model: "meta-llama/llama-3.1-8b-instruct",
    description:
      "General-purpose verdicts, balanced between speed and care. The default choice for most jobs.",
  },
  {
    key: "sage",
    pkEnv: "EVALUATOR_SAGE_PK",
    ansName: "arcwork-deepseek",
    model: "deepseek/deepseek-chat-v3-0324",
    description:
      "A reasoning-focused model that thinks through its verdict step by step before deciding. Slower, more deliberate — suited to jobs where the acceptance criteria are nuanced.",
  },
  {
    key: "swift",
    pkEnv: "EVALUATOR_SWIFT_PK",
    ansName: "arcwork-gemma",
    model: "google/gemma-3-4b-it",
    description:
      "A lightweight model tuned for fast, low-latency verdicts. Good fit for small, clearly-scoped jobs where a quick turnaround matters more than deep deliberation.",
  },
  {
    key: "hermes",
    pkEnv: "EVALUATOR_HERMES_PK",
    ansName: "arcwork-mistral",
    model: "mistralai/ministral-8b-2512",
    description:
      "Fine-tuned for careful instruction-following. Tends to weigh the job's stated acceptance criteria literally rather than judging on overall impression.",
  },

  // ── New 8 ──
  {
    key: "phi",
    pkEnv: "EVALUATOR_PHI_PK",
    ansName: "arcwork-phi",
    model: "microsoft/phi-4",
    description:
      "A small model that punches above its weight on reasoning. Good middle ground when you want careful judgment without the latency of a heavier model.",
  },
  {
    key: "qwen",
    pkEnv: "EVALUATOR_QWEN_PK",
    ansName: "arcwork-qwen",
    model: "qwen/qwen-2.5-7b-instruct",
    description:
      "Strong multilingual and technical comprehension — a solid fit for jobs with code, data, or non-English deliverables.",
  },
  {
    key: "nova",
    pkEnv: "EVALUATOR_NOVA_PK",
    ansName: "arcwork-nova",
    model: "openai/gpt-4o-mini",
    description:
      "Reliable, consistent verdicts with few surprises. A dependable default when you'd rather not think about which judge to pick.",
  },
  {
    key: "scout",
    pkEnv: "EVALUATOR_SCOUT_PK",
    ansName: "arcwork-scout",
    model: "meta-llama/llama-3.2-3b-instruct",
    description:
      "Ultra-fast, minimal-latency verdicts on a small model. Best for simple, unambiguous jobs where speed matters more than nuance.",
  },
  {
    key: "solar",
    pkEnv: "EVALUATOR_SOLAR_PK",
    ansName: "arcwork-solar",
    model: "upstage/solar-pro-3",
    description:
      "Tuned for tight instruction-following — judges strictly against what the job description actually asked for.",
  },
  {
    key: "zeus",
    pkEnv: "EVALUATOR_ZEUS_PK",
    ansName: "arcwork-zeus",
    model: "deepseek/deepseek-r1-distill-llama-70b",
    description:
      "The heaviest reasoner in the roster — works through its verdict at length before deciding. Slowest judge here, best for jobs where getting it right matters more than getting it fast.",
  },
  {
    key: "flash",
    pkEnv: "EVALUATOR_FLASH_PK",
    ansName: "arcwork-flash",
    model: "google/gemini-2.5-flash-lite",
    description:
      "Very fast and very cheap to run. Suited to high-volume, low-stakes jobs where you want a quick, no-frills verdict.",
  },
  {
    key: "yi",
    pkEnv: "EVALUATOR_YI_PK",
    ansName: "arcwork-yi",
    model: "z-ai/glm-4.5-air",
    description:
      "Handles long, detailed deliverables well — a long context window and a thorough read before it renders a verdict.",
  },
];
