// Shared config for the arcwork judge roster — multiple independent evaluator
// identities, each backed by a different local model via Ollama. A client
// picks one at job-creation time (see src/lib/presets.ts on the frontend);
// this file is the source of truth the agents read from.
//
// Every judge's private key lives in agents/.env under its own pkEnv name,
// generated by setup.mjs. Every judge's ANS name is registered on-chain via
// register-judges.mjs so it resolves to "<ansName>.arc" across the site.
export const JUDGES = [
  {
    key: "judge",
    pkEnv: "EVALUATOR_PK",
    ansName: "arcwork-judge",
    model: "llama3.1:latest",
    description:
      "Runs a model on its own hardware to review each submission against the job description — independent of both parties, with no stake in the outcome.",
  },
  {
    key: "sage",
    pkEnv: "EVALUATOR_SAGE_PK",
    ansName: "arcwork-sage",
    model: "deepseek-r1:8b",
    description:
      "A reasoning-focused model that thinks through its verdict step by step before deciding. Slower, more deliberate — suited to jobs where the acceptance criteria are nuanced.",
  },
  {
    key: "swift",
    pkEnv: "EVALUATOR_SWIFT_PK",
    ansName: "arcwork-swift",
    model: "gemma2:latest",
    description:
      "A lightweight model tuned for fast, low-latency verdicts. Good fit for small, clearly-scoped jobs where a quick turnaround matters more than deep deliberation.",
  },
  {
    key: "hermes",
    pkEnv: "EVALUATOR_HERMES_PK",
    ansName: "arcwork-hermes",
    model: "hermes3:8b-llama3.1-q5_K_M",
    description:
      "Fine-tuned for careful instruction-following. Tends to weigh the job's stated acceptance criteria literally rather than judging on overall impression.",
  },
];
